services:
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "job_db"
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    mysqldata: {}
